[package]
name = "lambdacube"
version = "0.1.0"
authors = ["felixzhuologist <felix.czhu@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
lalrpop-util = "0.15.2"
regex = "0.2.1"
wasm-bindgen = "0.2"
